name: measure-coverage

on:
  pull_request:
    path:
      branches:
        - master

env:
  JAVA_VERSION: 17
  COVERAGE_PERCENT: 60

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew test

      - name: Upload Report
        uses: 'actions/upload-artifact@v2'
        with:
          name: report.xml
          path: ${{ github.workspace }}/build/reportsJaCoCo/test/jacocoTestReport.xml

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/build/reportsJaCoCo/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: ${{ env.COVERAGE_PERCENT }}
          debug-mode: false
          title: Code Coverage
          update-comment: true

      - name: Block Merge if coverage is less than ${{ env.COVERAGE_PERCENT }}%
        if: ${{ steps.jacoco.outputs.coverage-overall < env.COVERAGE_PERCENT }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Overall coverage is less than ${{ env.COVERAGE_PERCENT }}%!\n actual ${{ steps.jacoco.outputs.coverage-overall }}%')