name: measure-coverage

on:
  pull_request:
    path:
      branches:
        - master

env:
  JAVA_VERSION: 17
  COVERAGE_PERCENT: 60

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 액션 런타임 환경에 JDK를 설치합니다
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      # 테스트 코드를 실행시킵니다
      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}  # 테스트가 실패하여도 Report를 보기 위해 `always`로 설정
        with:
          files: build/test-results/**/*.xml

      # 커버리지 결과를 PR에 업데이트합니다
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/build/reportsJaCoCo/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: ${{ env.COVERAGE_PERCENT }}
          debug-mode: false
          title: Code Coverage
          update-comment: true

      # 액션 완료 후, 커버리지 로그를 찍어줍니다
      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      # 커버리지가 N% 미만이면 빌드에 실패합니다
      - name: Block Merge if coverage is less than ${{ env.COVERAGE_PERCENT }}%
        if: ${{ steps.jacoco.outputs.coverage-overall < env.COVERAGE_PERCENT }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Overall coverage is less than ${{ env.COVERAGE_PERCENT }}%!')